#!/usr/bin/env python3
"""Generate the embedded p^2 q r class table for coupled_p2qr_scan.cpp.

The table is rebuilt from the two independent classifier implementations in
``../prime-support``.  For every canonical form it stores the local-index
matrix ``j[row][column]`` in the classifier's spanning-forest gauge, the row
roles, and the monomial-filter exclusion flag.  The generator checks that the
134 matrices are pairwise distinct and that every matrix satisfies the
weighted row constraints of the p^2 q r pattern.
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

PRIME_SUPPORT = Path(__file__).resolve().parents[1] / "prime-support"
sys.path.insert(0, str(PRIME_SUPPORT))

from p2qr_monomial_filter import (  # noqa: E402
    classify_arithmetic_filter,
    local_indices,
)
from three_block_p2qr_signatures import classify_all  # noqa: E402


def build_table() -> list[dict[str, object]]:
    patterns: dict[str, tuple[int, int | None, int | None]] = {}
    for result in classify_all():
        for form in result.canonical_forms:
            patterns[form] = result.pattern
    excluded_map = {
        result.canonical_form: bool(result.excluded)
        for result in classify_arithmetic_filter()
    }

    classes = []
    for form, pattern in sorted(patterns.items()):
        indices = local_indices(pattern, form)
        for row in range(3):
            values = sorted(abs(value) for value in indices[row])
            if row == 0:
                expect = [1, 2, 2, 2]
            else:
                expect = [0, 1, 1, 1] if 0 in values else [1, 1, 1, 1]
            if values != expect:
                raise AssertionError((form, row, indices[row]))
        roles = []
        for row in range(3):
            k = 2 if row == 0 else 1
            exceptional = [
                column
                for column in range(4)
                if abs(indices[row][column]) != k
            ]
            if not exceptional:
                roles.append("F")
            elif len(exceptional) == 1:
                roles.append("C" if exceptional[0] < 2 else "E")
            else:
                raise AssertionError((form, row, indices[row]))
        classes.append(
            {
                "form": form,
                "idx": indices,
                "excluded": excluded_map[form],
                "role": "".join(roles),
            }
        )

    matrices = {tuple(map(tuple, c["idx"])) for c in classes}
    if len(matrices) != len(classes):
        raise AssertionError("canonical j-matrices are not pairwise distinct")
    return classes


def main() -> int:
    classes = build_table()
    lines = []
    for c in classes:
        rows = ",".join(
            "{" + ",".join(str(v) for v in row) + "}" for row in c["idx"]
        )
        lines.append(
            f'  {{"{c["form"]}", "{c["role"]}", '
            f'{str(c["excluded"]).lower()}, '
            f'{{{rows}}}}},'
        )
    table = "\n".join(lines)
    header = (
        "// Generated by gen_class_table.py; do not edit by hand.\n"
        "// Each row: canonical form, row roles (p,q,r), monomial-filter\n"
        "// exclusion flag, and local indices j[row][column] with rows\n"
        "// (p,q,r) and columns (corner0, corner1, edge2, edge3).\n"
        "#ifndef COUPLED_P2QR_CLASS_TABLE_H\n"
        "#define COUPLED_P2QR_CLASS_TABLE_H\n"
        "#include <cstddef>\n"
        "struct P2QRClass {\n"
        "  const char* form;\n"
        "  const char* role;\n"
        "  bool excluded;\n"
        "  int j[3][4];\n"
        "};\n"
        "inline constexpr P2QRClass kP2QRClasses[] = {\n"
        f"{table}\n"
        "};\n"
        "inline constexpr std::size_t kP2QRClassCount =\n"
        "    sizeof(kP2QRClasses) / sizeof(kP2QRClasses[0]);\n"
        "#endif\n"
    )
    out = Path(__file__).resolve().parent / "class_table.h"
    out.write_text(header)
    print(f"wrote {out} with {len(classes)} classes")
    print("roles:", dict(Counter(c["role"] for c in classes)))
    print(
        "filter survivors by role:",
        dict(
            Counter(c["role"] for c in classes if not c["excluded"])
        ),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
